name: Auto-generate IME dictionaries

on:
  push:
    paths:
      - 'base_names.csv'
      - 'base_words.csv'
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt || true

      - name: Generate IME dictionary files
        run: python generate_all.py

      - name: Commit and push generated files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add 100kanojo_*dic.txt
          git commit -m "chore: auto-generate IME dictionaries [skip ci]" || echo "No changes to commit"
          git push
