name: Auto-generate IME dictionaries

on:
  workflow_dispatch:
    inputs:
      volume:
        description: "単行本の巻数 (Y)"
        required: true
        default: "1"

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # tagや履歴を参照するため

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt || true

      - name: Generate IME dictionary files
        run: python generate_all.py

      - name: Get previous release
        id: prev
        run: |
          PREV=$(gh api repos/${{ github.repository }}/releases/latest --jq .tag_name || echo "")
          echo "prev_tag=$PREV" >> $GITHUB_ENV
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Calculate new version
        id: version
        run: |
          MAJOR=1
          VOLUME=${{ github.event.inputs.volume }}

          if [ -z "$prev_tag" ]; then
            PATCH=0
          else
            PREV_Y=$(echo $prev_tag | cut -d. -f2 | tr -d v)
            PREV_Z=$(echo $prev_tag | cut -d. -f3)
            if [ "$PREV_Y" = "$VOLUME" ]; then
              PATCH=$((PREV_Z + 1))
            else
              PATCH=0
            fi
          fi

          VERSION="v${MAJOR}.${VOLUME}.${PATCH}"
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "VOLUME=$VOLUME" >> $GITHUB_ENV
          echo "Version = $VERSION"

      - name: Commit generated files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add 100kanojo_*dic.txt
          git commit -m "chore: auto-generate IME dictionaries for v${{ steps.version.outputs.VERSION }}" || echo "No changes to commit"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.version.outputs.VERSION }}
          name: "Release ${{ steps.version.outputs.VERSION }}"
          body: |
            このリリースは **単行本${{ steps.version.outputs.VOLUME }}巻** に対応しています。
            自動生成された IME 辞書ファイル（通常版 + _Usami版）が含まれています。
          files: |
            100kanojo_*dic.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
