name: Auto-generate IME dictionaries

on:
  push:
    branches: [ main ]  # mainブランチにpushされたときのみ実行

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      # 1. リポジトリをチェックアウト
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: true

      # 2. Python をセットアップ
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # 3. generate_all.py を実行して6ファイルを生成
      - name: Generate IME dictionary files
        run: python generate_all.py

      # 4. 生成されたファイルをコミット＆push（変更があれば）
      - name: Commit and push generated files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add 100kanojo_*_dic*.txt
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Auto-generate IME & Usami files"
            git push
