name: Generate IME Dictionaries

on:
  workflow_dispatch:  # 手動実行のみ

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      # 1. リポジトリをチェックアウト（書き込み権限付き）
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      # 2. Python セットアップ
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      # 3. 必要なパッケージをインストール
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || echo "No requirements.txt found"

      # 4. IME 辞書ファイル生成
      - name: Generate dictionaries
        run: python generate_all.py

      # 5. 変更を Git にコミット
      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add base/*.csv 100kanojo_*dic.txt
          git commit -m "chore: auto-generate IME dictionaries" || echo "No changes to commit"

      # 6. 変更を main ブランチにプッシュ
      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main

